### ISSUE TITLE
No information about required GPS mobile vision depdency

### ISSUE THREAD

**Issue by jszczygiel** [KingsMentor/MobileVisionBarcodeScanner#1]
So now if I import MobileVisionBarcodeScanner dependency to project it will crash at runtime because 

`compile "com.google.android.gms:play-services-vision:9.6.1"`

is missing

**Comment by KingsMentor** [comment]
actually, the library already uses :
 `compile 'com.google.android.gms:play-services-vision:9.4.0'`
you don't need to include it again in your `build.gradle` . You can clone to project to update the version of the mobile vision api (which might be the issue) . Would make an update in the next release.

**Comment by jszczygiel** [comment]
Yes but if you use
`compile 'com.github.KingsMentor:MobileVisionBarcodeScanner:v1.2'`

play-services-vision won't be fetched. If you want this dependency to be carried over with your lib you have to use transitive option:

`compile('com.github.KingsMentor:MobileVisionBarcodeScanner:v1.2') {
    transitive = true;
}`

So you can update README in two ways:
1. Add transitive compile
or
2. Indicate underlaying dependency.

**Comment by KingsMentor** [comment]
Great. 
Would update the README accordingly.
Thanks.

**Comment by jszczygiel** [comment]
:thumbsup:
