### ISSUE TITLE
Make the camera screen full screen

### ISSUE THREAD

**Issue by freebumba27** [KingsMentor/MobileVisionBarcodeScanner#10]
I don't need the control at the bottom. How should I remove it and make the camera preview in the full screen?

**Comment by freebumba27** [comment]
The problem was with resolution. That's why it's not full screen. Now I have played with it and opening the camera in low resolution. Now it's full screen.

**Comment by mickey35vn** [comment]
// Creates and starts the camera.  Note that this uses a higher resolution in comparison
        // to other detection examples to enable the barcode detector to detect small barcodes
        // at long distances.
        CameraSource.Builder builder = new CameraSource.Builder(getContext(), barcodeDetector)
                .setFacing(CameraSource.CAMERA_FACING_BACK)
                .setRequestedPreviewSize(1600, 1024)
                .setRequestedFps(15.0f);

>>> I think that's reason why it isn't fullscreen
