### ISSUE TITLE
Flash nos turning off!

### ISSUE THREAD

**Issue by gabrielnra** [KingsMentor/MobileVisionBarcodeScanner#13]
```
public void flashlight(View view){
        Boolean flashIsOn = barcodeCapture.isShowFlash();
        if(!flashIsOn){
            barcodeCapture.setShowFlash(true);
        }else{
            barcodeCapture.setShowFlash(false);
        }
        barcodeCapture.refresh();
 }
```

I'm implementing a button inside the view that when clicked, checks the flash status and if off, turns it off and if on, turns it off.

The turning ON part is ok, but turning OFF doesn't work.

Can you help me?

**Comment by haemi** [comment]
did you find a solution for this?

**Comment by haemi** [comment]
the problem is here, but I don't know how I can solve that in my project yet:

`BarcodeCapture:230` should NOT be

`mCameraSource.setFlashMode(isShowFlash() ? Camera.Parameters.FLASH_MODE_TORCH : null);`

but

`mCameraSource.setFlashMode(isShowFlash() ? Camera.Parameters.FLASH_MODE_TORCH : Camera.Parameters.FLASH_MODE_OFF);`

**Comment by gabrielnra** [comment]
I`m not being able to fix this. Could you?

**Comment by haemi** [comment]
yes, please see my pull request

**Comment by android-guilherme** [comment]
Waiting for that update....

**Comment by KingsMentor** [comment]
@android-guilherme just push an update that fixed these issues. About to close up all issues. Will release the update afterwards.

**Comment by android-guilherme** [comment]
@KingsMentor Thanks for that! Really thanks!

**Comment by KingsMentor** [comment]
a new released is available now. 
```xml
	dependencies {
	        compile 'com.github.KingsMentor:MobileVisionBarcodeScanner:2.0.0'
	}
```

**Comment by android-guilherme** [comment]
@KingsMentor Yes! I'm using that now. So much better! Again, Thanks for that awesome job.

**Comment by PrashantMangale** [comment]
@haemi Hello, how you initialize mCameraSource?
I am not getting how to do that. I have used previous code of @gabrielnra to on/off Flash while scan.
It takes value on/off from Shared Preferences and will call to setShowFlash() method on it with respective value true/false.
But its not working, even library is updated to latest version. Help me to solve this issue.
