### ISSUE TITLE
java.lang.NoClassDefFoundError: BarcodeDetectorOptions

### ISSUE THREAD

**Issue by pedrofsn** [KingsMentor/MobileVisionBarcodeScanner#22]
java.lang.NoClassDefFoundError: com.google.android.gms.vision.barcode.internal.client.BarcodeDetectorOptions

I'm with gradle import like: 
`compile('com.github.KingsMentor:MobileVisionBarcodeScanner:v1.2') { transitive = true; }`

**Comment by KingsMentor** [comment]
If you have other version of google-play-services, I suggest you add to gradle it like this
```
compile 'com.google.android.gms:play-services-vision:[play-version]'
    compile('com.github.KingsMentor:MobileVisionBarcodeScanner:v1.2') {
        transitive = true;
        exclude group: 'com.google.android.gms'
    }
```

**Comment by pedrofsn** [comment]
Ok.

**Comment by sudheeshde** [comment]
are you able to fix this ?

**Comment by eden-investing** [comment]
I'm still getting this crash:
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzdcc;
                                                       at com.google.android.gms.vision.barcode.BarcodeDetector$Builder.<init>(Unknown Source)

In my gradle:
implementation ('xyz.belvi.mobilevision:barcodescanner:2.0.3') {
        transitive = true
        exclude group: 'com.google.android.gms'
    }
