### ISSUE TITLE
Barcode auto scan not working

### ISSUE THREAD

**Issue by PrashantMangale** [KingsMentor/MobileVisionBarcodeScanner#23]
Hello Sir,
The library is very useful for me. But i am facing one issue while scanning barcode. In some devices barcode not getting scanned automatically. I have to click on camera to get that code. Samsung devices having this issue. Even for some MI devices Redmi 1S, MI 3. 
I have given my code. Please check and let me know if i did something wrong.
Code as below : 
1. This is java code : 

 barcodeCapture = (BarcodeCapture) getSupportFragmentManager().findFragmentById(R.id.barcode);
        barcodeCapture.setRetrieval(this);

    @Override
    public void onRetrieved(final Barcode barcode) {
        Log.d("Barcode", "Barcode read: " + barcode.displayValue);
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                AlertDialog.Builder builder = new AlertDialog.Builder(ScanBarcodeActivity.this)
                        .setTitle("code retrieved")
                        .setMessage(barcode.displayValue)
                        .setPositiveButton("Ok", new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                arrayListBarcode.add(barcode.displayValue);
                                dialog.dismiss();
                            }
                        })
                        .setCancelable(false);
                builder.show();
            }
        });
    }

XML Code : 
`
<fragment
        android:id="@+id/barcode"
        android:name="com.google.android.gms.samples.vision.barcodereader.BarcodeCapture"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        app:gvb_auto_focus="true"
        app:gvb_code_format="all_format"
        app:gvb_flash="true"
        app:gvb_rect_colors="@array/rect_color"/>
`

I am waiting for response. I have an urgent solution for it.

**Comment by KingsMentor** [comment]
Hello, Disable touch callback from xml to make this work

**Comment by KingsMentor** [comment]
```
<fragment
            android:id="@+id/barcode"
            android:name="com.google.android.gms.samples.vision.barcodereader.BarcodeCapture"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            app:gvb_auto_focus="true"
            app:gvb_code_format="all_format"
            app:gvb_flash="false"
            app:gvb_touch="false"
            app:gvb_rect_colors="@array/rect_color" />
```

`gvb_touch` is false to disable camera touch

**Comment by PrashantMangale** [comment]
It's working now. But I have to test on other devices. That i will do and get back to you.
One more thing i want to ask can i pause scan if i already scanned one barcode. Because if i keep camera on single barcode then it keep scanning repeatedly.
So what i want to do is that after scanning one barcode it should stop/pause scanning until i close that popup.
Please help me.

**Comment by KingsMentor** [comment]
Hello @PrashantMangale . This issue has just been fixed. I have added `stopScanning` on BarcodeCapture class. This will enable you stop scanning at any point in time. This will be available in the next release. For now, pull from master to get the update. Thanks.
