### ISSUE TITLE
Rectange draw did not works 

### ISSUE THREAD

**Issue by abhishekchaubey** [KingsMentor/MobileVisionBarcodeScanner#24]
Great work 👍 
 i have used your sample but unable to draw a rectangle while accessing QR and any other type of barcode while scanning.

i am using this   `app:gvb_rect_colors="@array/rect_color"`  but no help.

Device using is **Xiomi note 3 , android version 4.4;**

**Comment by KingsMentor** [comment]
Kindly ensure gvb_draw is true.

`app:gvb_draw="true"`

**Comment by Laya303** [comment]
It still doesn't work.
