### ISSUE TITLE
exception when call barcodeCapture.stopScanning()

### ISSUE THREAD

**Issue by martialDevOrange** [KingsMentor/MobileVisionBarcodeScanner#25]
when I call **stopScanning** function, i have this error many times 
``OpenCameraSource: Exception thrown from receiver.
                                                                          java.lang.IllegalStateException: Detector processor must first be set with setProcessor in order to receive detection results.
                                                                              at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
                                                                              at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1222)
                                                                              at java.lang.Thread.run(Thread.java:818)``

I used the last version 2.0.0

**Comment by KingsMentor** [comment]
@martialowt  can you share a snippet of what the code.

**Comment by martialDevOrange** [comment]
Hi,

I just call  when a barcode was found:
    @Override
    public void onRetrieved(final Barcode barcode) {

        getActivity().runOnUiThread(new Runnable() {
            @Override
            public void run() {
                AlertDialog.Builder builder = new
AlertDialog.Builder(mContext)
                        .setTitle("code retrieved")
                        .setMessage(barcode.displayValue);
                builder.show();
            }
        });

        mBarcodeCapture.stopScanning();

    }

I am on a fragment, and i wan't to stop scanning when the code was found

2017-08-16 16:23 GMT+02:00 Nosakhare Belvi <notifications@github.com>:

**Comment by KingsMentor** [comment]
just made a fix that might work for you.

Try this compile build instead and kindly give feedback if it resolved the issue.

`compile 'com.github.KingsMentor:MobileVisionBarcodeScanner:010c5e7f60'`

**Comment by martialDevOrange** [comment]
exactly the same error, no change...

**Comment by KingsMentor** [comment]
here is another you might want to try. Work's perfectly well on my test cases.
```xml	
dependencies {
	        compile 'com.github.KingsMentor:MobileVisionBarcodeScanner:ce537187e7'
	}
```

**Comment by martialDevOrange** [comment]
the error persist for me, i see that the same was corrected on another qr Library : https://github.com/nisrulz/qreader/issues/8

**Comment by KingsMentor** [comment]
yea. saw that too and made necessary fixes. Will take a more concrete look into this and provide a fix as soon as possible.

**Comment by hknn** [comment]
I get the same error. when will you fix

**Comment by KingsMentor** [comment]
@hknn the new release fixed this issue. kindly confirm se we can close this issue.

**Comment by chefmech** [comment]
Can you please tell me what was the problem and what have you done to fix it?
I have the same problem, not with your lib, but with the google api.

I already check barcodeDetectror.isOperational, but that seems not to be the soloution...

**Comment by albert0m** [comment]
still broken for me, did anyone else confirm it as fixed?

**Comment by sanjeet007** [comment]
what is going on closing without fix
Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
