### ISSUE TITLE
how to Resume Camera to start scanning again after stopping

### ISSUE THREAD

**Issue by kprathap23** [KingsMentor/MobileVisionBarcodeScanner#29]

**Comment by KingsMentor** [comment]
@kprathap23  starting from v2.0.1, there is `pause()` and `resume()` for this.

Also, there is `barcodeCapture.refresh(boolean forceRefresh)` in case you want to force some new configurations.

**Comment by kprathap23** [comment]
Great...Thanks for great library

**Comment by kprathap23** [comment]
Can u please release this version to use these latest methods 2.0.1

**Comment by KingsMentor** [comment]
@kprathap23 it is already available and release. Kindly use the current version
