### ISSUE TITLE
Detecting imaginary codes

### ISSUE THREAD

**Issue by borjaruiz** [KingsMentor/MobileVisionBarcodeScanner#8]
Hi, when I leave the mobile on the table, and the camera can't detect anything (black screen), it sometimes read an imaginary barcode, randomly.

**Comment by KingsMentor** [comment]
hello @borjaruiz , how do I recreate the bug so I can test and fix

**Comment by shivamverma676** [comment]
Hi, I am facing the same issue. This bug is not actually closed. is it because of supported format?
