### ISSUE TITLE
Can't open camera first time

### ISSUE THREAD

**Issue by Bekakk** [KingsMentor/MobileVisionBarcodeScanner#9]
Hi
I'm using your library.I have one problem.First time i can't open camera in marshmallow.I clicked Allow but i can't open camera,Second time camera working perfect

**Comment by freebumba27** [comment]
Still now no solution? :-(

**Comment by KingsMentor** [comment]
@Bekakk Make sure you can camera permission granted for marshmallow devices. This should work.

**Comment by freebumba27** [comment]
@KingsMentor Even I grant it first time it does not work.

> if(!hasPermissions(getContext(), PERMISSIONS)) {
            ActivityCompat.requestPermissions(getActivity(), PERMISSIONS, CAMERA_PERMISSION_REQUEST_CODE);
        } else {
             barcodeCapture = (BarcodeCapture) getChildFragmentManager().findFragmentById(barcode);
             barcodeCapture.setRetrieval(this);
        }

**Comment by KingsMentor** [comment]
@freebumba27 . Thanks for pointing this out. The problem is the xml has already been inflated and if the permission has not been granted, the app wouldn't be able to use the camera.  Here is a quick fix:
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/root_blur_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <include
        android:id="@+id/mainLayout"
        layout="@layout/toolbar" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/mainLayout"
        android:background="#000"
        android:gravity="center"
        android:orientation="vertical"
        android:paddingTop="50dp">

        <LinearLayout
            android:id="@+id/cam_layout"
            android:layout_width="300dp"
            android:layout_height="300dp"
            android:orientation="vertical"/>


        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:padding="16dp"
            android:text="Align the QR Code/bar code within the frame to scan"
            android:textColor="#fff" />

    </LinearLayout>

</RelativeLayout>
```

Notice that the barcode  fragment in not in this xml. 
I moved it to a seperated xml file : `cam_layout.xml` and inflate it only when the permission has been granted.

Achieved that with this snippet:

```
View camView = LayoutInflater.from(this).inflate(R.layout.cam_layout, null, false);
                ((LinearLayout) findViewById(R.id.cam_layout)).addView(camView);
                barcodeCapture = (BarcodeCapture) getSupportFragmentManager().findFragmentById(R.id.barcode);
                barcodeCapture.setRetrieval(this);
```

and here is `cam_layout.xml`

```
<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/barcode"
    android:name="com.google.android.gms.samples.vision.barcodereader.BarcodeCapture"
    android:layout_width="300dp"
    android:layout_height="300dp"
    app:gvb_auto_focus="true"
    app:gvb_code_format="all_format"
    app:gvb_flash="false" />
```

A more usable update will be pushed but this should work for you.

**Comment by KingsMentor** [comment]
@freebumba27 does this works for you ?

**Comment by freebumba27** [comment]
Yes it worked perfectly. I will suggest you to make the camera full screen. I have tested the app in S7 edge it's taking back area at the bottom of the screen. I think it's duo to resolution. If you can fix this part and update the dependency then this one of the best Lib based on MobileVison
